### ISSUE TITLE
 Get post info 

### ISSUE THREAD

**Issue by 89z** [KagChi/instagram-api.js#3]
If I have a post such as this:

https://www.instagram.com/p/CT-cnxGhvvO/

How do I get the info for this post? Sorry for the basic question, but I have looked over the API and am not seeing a way to do this.

**Comment by KagChi** [comment]
will be implemented in 2-3 days

**Comment by KagChi** [comment]
already implemented

**Comment by 89z** [comment]
How to do it?

**Comment by KagChi** [comment]
why dont just read the source?

**Comment by KagChi** [comment]
and also update your `instagram-api.js` to use the post info
